// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_pt
double rcpp_pt(double q, double nu, double delta);
RcppExport SEXP _NCdistributions_rcpp_pt(SEXP qSEXP, SEXP nuSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_pt(q, nu, delta));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_qt
double rcpp_qt(double p, double nu, double delta);
RcppExport SEXP _NCdistributions_rcpp_qt(SEXP pSEXP, SEXP nuSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_qt(p, nu, delta));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_pchisq
double rcpp_pchisq(double q, double nu, double delta);
RcppExport SEXP _NCdistributions_rcpp_pchisq(SEXP qSEXP, SEXP nuSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_pchisq(q, nu, delta));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_pchisq_upper
double rcpp_pchisq_upper(double q, double nu, double delta);
RcppExport SEXP _NCdistributions_rcpp_pchisq_upper(SEXP qSEXP, SEXP nuSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_pchisq_upper(q, nu, delta));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_qchisq
double rcpp_qchisq(double p, double nu, double delta);
RcppExport SEXP _NCdistributions_rcpp_qchisq(SEXP pSEXP, SEXP nuSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_qchisq(p, nu, delta));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_chisq_ncp
double rcpp_chisq_ncp(double nu, double q, double p);
RcppExport SEXP _NCdistributions_rcpp_chisq_ncp(SEXP nuSEXP, SEXP qSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_chisq_ncp(nu, q, p));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_chisq_nu
double rcpp_chisq_nu(double ncp, double q, double p);
RcppExport SEXP _NCdistributions_rcpp_chisq_nu(SEXP ncpSEXP, SEXP qSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type ncp(ncpSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_chisq_nu(ncp, q, p));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_pf
double rcpp_pf(double q, double nu1, double nu2, double ncp);
RcppExport SEXP _NCdistributions_rcpp_pf(SEXP qSEXP, SEXP nu1SEXP, SEXP nu2SEXP, SEXP ncpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type nu1(nu1SEXP);
    Rcpp::traits::input_parameter< double >::type nu2(nu2SEXP);
    Rcpp::traits::input_parameter< double >::type ncp(ncpSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_pf(q, nu1, nu2, ncp));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_qf
double rcpp_qf(double p, double nu1, double nu2, double ncp);
RcppExport SEXP _NCdistributions_rcpp_qf(SEXP pSEXP, SEXP nu1SEXP, SEXP nu2SEXP, SEXP ncpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type nu1(nu1SEXP);
    Rcpp::traits::input_parameter< double >::type nu2(nu2SEXP);
    Rcpp::traits::input_parameter< double >::type ncp(ncpSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_qf(p, nu1, nu2, ncp));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_pbeta
double rcpp_pbeta(double q, double a, double b, double ncp);
RcppExport SEXP _NCdistributions_rcpp_pbeta(SEXP qSEXP, SEXP aSEXP, SEXP bSEXP, SEXP ncpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type ncp(ncpSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_pbeta(q, a, b, ncp));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_qbeta
double rcpp_qbeta(double p, double a, double b, double ncp);
RcppExport SEXP _NCdistributions_rcpp_qbeta(SEXP pSEXP, SEXP aSEXP, SEXP bSEXP, SEXP ncpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type ncp(ncpSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_qbeta(p, a, b, ncp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_NCdistributions_rcpp_pt", (DL_FUNC) &_NCdistributions_rcpp_pt, 3},
    {"_NCdistributions_rcpp_qt", (DL_FUNC) &_NCdistributions_rcpp_qt, 3},
    {"_NCdistributions_rcpp_pchisq", (DL_FUNC) &_NCdistributions_rcpp_pchisq, 3},
    {"_NCdistributions_rcpp_pchisq_upper", (DL_FUNC) &_NCdistributions_rcpp_pchisq_upper, 3},
    {"_NCdistributions_rcpp_qchisq", (DL_FUNC) &_NCdistributions_rcpp_qchisq, 3},
    {"_NCdistributions_rcpp_chisq_ncp", (DL_FUNC) &_NCdistributions_rcpp_chisq_ncp, 3},
    {"_NCdistributions_rcpp_chisq_nu", (DL_FUNC) &_NCdistributions_rcpp_chisq_nu, 3},
    {"_NCdistributions_rcpp_pf", (DL_FUNC) &_NCdistributions_rcpp_pf, 4},
    {"_NCdistributions_rcpp_qf", (DL_FUNC) &_NCdistributions_rcpp_qf, 4},
    {"_NCdistributions_rcpp_pbeta", (DL_FUNC) &_NCdistributions_rcpp_pbeta, 4},
    {"_NCdistributions_rcpp_qbeta", (DL_FUNC) &_NCdistributions_rcpp_qbeta, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_NCdistributions(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
