# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_pt <- function(q, nu, delta, lower) {
    .Call('_NCdistributions_rcpp_pt', PACKAGE = 'NCdistributions', q, nu, delta, lower)
}

rcpp_qt <- function(p, nu, delta, lower) {
    .Call('_NCdistributions_rcpp_qt', PACKAGE = 'NCdistributions', p, nu, delta, lower)
}

rcpp_pchisq <- function(q, nu, delta, lower) {
    .Call('_NCdistributions_rcpp_pchisq', PACKAGE = 'NCdistributions', q, nu, delta, lower)
}

rcpp_qchisq <- function(p, nu, delta, lower) {
    .Call('_NCdistributions_rcpp_qchisq', PACKAGE = 'NCdistributions', p, nu, delta, lower)
}

rcpp_chisq_ncp <- function(nu, q, p) {
    .Call('_NCdistributions_rcpp_chisq_ncp', PACKAGE = 'NCdistributions', nu, q, p)
}

rcpp_chisq_nu <- function(ncp, q, p) {
    .Call('_NCdistributions_rcpp_chisq_nu', PACKAGE = 'NCdistributions', ncp, q, p)
}

rcpp_pf <- function(q, nu1, nu2, delta, lower) {
    .Call('_NCdistributions_rcpp_pf', PACKAGE = 'NCdistributions', q, nu1, nu2, delta, lower)
}

rcpp_qf <- function(p, nu1, nu2, delta, lower) {
    .Call('_NCdistributions_rcpp_qf', PACKAGE = 'NCdistributions', p, nu1, nu2, delta, lower)
}

rcpp_pbeta <- function(q, a, b, delta, lower) {
    .Call('_NCdistributions_rcpp_pbeta', PACKAGE = 'NCdistributions', q, a, b, delta, lower)
}

rcpp_qbeta <- function(p, a, b, delta, lower) {
    .Call('_NCdistributions_rcpp_qbeta', PACKAGE = 'NCdistributions', p, a, b, delta, lower)
}

